BatchProcessor:
    description: 'DirectX-Voxel project config files'
    workDirectory: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\Resources\Config'
    files:
      - Assets\assets_base.yaml
      - Assets\assets_material.yaml
      - Assets\assets_mesh.yaml
      - Assets\assets_shader.yaml
      - Assets\assets_terrain.yaml
      - Assets\assets_texture.yaml
      - Assets\assets_texture_map.yaml
      - Assets\assets_vertex.yaml
      - camera_config.yaml
      - engine_config.yaml
      - Engine\engine_render_pass.yaml
      # - Engine\engine_jobs.yaml
      - Engine\Pipeline\engine_render_state.yaml
      - Engine\Pipeline\pipeline_slots_contract.yaml
      - Game\game_base.yaml
      - Game\game_object.yaml
      - Game\game_object_base.yaml
      - Game\game_system.yaml
      - services_config.yaml
      - Game\Biomes\game_biomes.yaml
      - Game\Terrain\terrain_engines.yaml
      - Game\Terrain\geometry_engines.yaml
      # - Game\Biomes\game_biomes_textures.yaml
