# engine_render_pass.yaml
Config:
  Base:
    RenderPass:
      ShadowPass:
        id: 1
        enabled: true
        shader_name: ShadowMapShader
        rasterizedState: RasterizedShadowPass
        viewPortState: ViewportShadow
        stencilState: StencilViewShadow
        stencilDef: StencilStateRegular
        shaderViewState: ShaderViewShadow
        shadowTextureView: none
        blendState: DisabledBlending
        primitiveTopology: 4 # D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST
        resolution: 2048 # Resolution for shadow map

      MainColorPass:
        id: 2
        enabled: true
        shader_default: PBRShadowShader
        rasterizedState: RasterizedMainColorPass
        viewPortState: ViewportMainColor
        stencilState: StencilViewMainColor
        stencilDef: none
        shaderViewState: none
        shadowTextureView: StencilViewShadow
        blendState: none
        primitiveTopology: 4 # D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST

      UIPass:
        id: 8
        enabled: true
        shader_default: ShaderTextUI
        rasterizedState: RasterizedUIPass
        viewPortState: ViewportUI
        stencilState: none
        stencilDef: StencilStateUI
        shaderViewState: none
        shadowTextureView: none
        blendState: BlendingUI
        primitiveTopology: 4 # D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST

      SkyboxPass:
        id: 16
        enabled: true
        shader_default: PBRShadowShader
        rasterizedState: RasterizedMainColorPass
        viewPortState: ViewportMainColor
        stencilState: StencilViewMainColor
        stencilDef: none
        shaderViewState: none
        shadowTextureView: StencilViewShadow
        blendState: none
        primitiveTopology: 4 # D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST

Definition:
  Default:
    language: 1 # C++
    type: "Class"
    needs_register: true
    file_level: 3
    register_include: "REGISTER_CONFIG_TYPE"
    register_macro: "REGISTER_CONFIG_MACRO"
    interface_name: "ConfigBase"
    class_suffix: "Config"
    class_prefix: ""
    inherits_properties:
        - type
        - dependencies
    output_path: 'c:\Users\joaqu\source\repos\DirectX-Voxelado\src\Engine\Core\Config\Base\'
    #output_path: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\TestConfig\Game\'
