Config:
  Game:
      GameEngine:
        services_init_order:
          -
          # - UIDebug
          # - TestingBasic2
          # - AxisXYZ
          # - Skybox
          # - World
          # - Terrain
          # - Physics
          # - Biome
          # - Lighting
          # - Cycle
          # - Wheather
        services_render_order:
          -
          # - UIDebug
          # - TestingBasic2
          # - AxisXYZ
          # - Skybox
          # - World
          # - Terrain
          # - Physics
          # - Biome
          # - Lighting
          # - Cycle
          # - Wheather
      TestingBasic2:
          name: "TestingBasicManager"
          active: true
          version: "1.0.0"
          type: "TestingBasic2"
          description: "Un triángulo de pruebas básicas."
      AxisXYZ:
          name: "AxisManager"
          active: true
          type: "AxisXYZ"
      World:
          name: "WorldMananger"
          active: true
          version: "1.0.0"
          type: "VoxelWorld"
          description: "Un juego de aventura en un mundo voxelizado."
          respawnTime: 5
      Terrain:
          name: "TerrainManager"
          active: true
          version: "1.0.0"
          type: "ProceduralTerrain"
          seed: 1234567890
      Skybox:
          name: "Skybox"
          active: true
          version: "1.0.0"
          type: "DefaultSkybox"
      Physics:
          name: "PhysicManager"
          active: true
          version: "1.0.0"
          type: "BasicPhysics"
          properties:
          gravity: [0.0, -9.81, 0.0] 
      Biome:
          name: "BiomwManager"
          active: true
          version: "1.0.0"
          type: "ForestBiome"
          properties:
          vegetation_density: 0.8
          wildlife_density: 0.5
      Lighting:
          name: "LightManager"
          active: true
          version: "1.0.0"
          type: "DynamicLighting"
          properties:
          ambient_light: [0.2, 0.2, 0.2]
          directional_light: [1.0, 1.0, 1.0]
          shadows: true
      Cycle:
          name: "CycleManager"
          active: true
          version: "1.0.0"
          type: "DayNightCycle"
          day_night_cycle: true
          day_night_cycle_speed: 0.1
      Wheather:
          name: "WheatherManager"
          active: true
          version: "1.0.0"
          type: "DynamicWeather"
          properties:
          rain_intensity: 0.3
          snow_intensity: 0.1
          fog_density: 0.2