# assets_texture.yaml
Config:
  Asset:
    Texture:
      TextureTextUI:
        type: "TextureAsset"
        map: "TextureTextUIMap"
        dependencies:
          - DeviceManager
          - TextureAsset 
      TextureGrassDiffuse:
        type: "TextureAsset"
        map: "TextureGrassDiffuseMap"
        dependencies:
          - DeviceManager
          - TextureAsset 
      DefaultSkybox:
        type: "TextureAsset"
        map: "DefaultSkyboxMap"
        rotation_speed: 0.05 # Propiedad específica del skybox
        dependencies:
          - TextureAsset
Definition:
  Default:
    language: 1 # C++
    type: "Class"
    needs_register: true
    file_level: 3
    register_include: "REGISTER_CONFIG_TYPE"
    register_macro: "REGISTER_CONFIG_MACRO"
    interface_name: "ITextureConfig"
    class_suffix: "Config"
    class_prefix: ""
    object_class:
        maps: ""
    inherits_properties:
        - type
        - definition
        - map
        - dependencies
    # output_path: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\TestConfig\Assets\'
    output_path: 'c:\Users\joaqu\source\repos\DirectX-Voxelado\src\Engine\Core\Config\Assets\'