# assets_texture_map.yaml
Config:
  Asset:
    TextureMap:
      TextureTextUIMap:
        texture_type: "JPG"
        albedo: "Assets\\Textures\\UI\\DejaVuSansMono.jpg"
      TextureGrassDiffuseMap:
         texture_type: "JPG"
         albedo: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Textures\\Rock\\Coast_sand_rock\\coast_sand_rocks_02_diff_4k.jpg"
         normal: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Textures\\Rock\\Coast_sand_rock\\coast_sand_rocks_02_nor_dx_4k.jpg"
         roughness: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Textures\\Rock\\Coast_sand_rock\\coast_sand_rocks_02_rough_4k.jpg"
         metallic: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Textures\\Rock\\Coast_sand_rock\\coast_sand_rocks_02_arm_4k.jpg"
         ao: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Textures\\Rock\\Coast_sand_rock\\coast_sand_rocks_02_ao_4k.jpg"
      DefaultSkyboxMap:
        texture_type: "CUBEMAP"
        albedo: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Skybox\\defaultSkybox.dds"
Definition:
  Default:
    language: 1 # C++
    type: "Class"
    needs_register: true
    file_level: 3
    register_include: "REGISTER_CONFIG_TYPE"
    register_macro: "REGISTER_CONFIG_MACRO"
    interface_name: "ITextureMapConfig"
    class_suffix: "Config"
    class_prefix: ""
    object_class:
        maps: ""
    inherits_properties:
        - type
        - definition
        - albedo
        - normal
        - roughness
        - metallic
        - ao
        - texture_type
        - dependencies
    # output_path: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\TestConfig\Assets\'
    output_path: 'c:\Users\joaqu\source\repos\DirectX-Voxelado\src\Engine\Core\Config\Assets\'