# assets_shaders.yaml
Config:
  Asset:
    Shader:
      ShaderTextUI:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TextShader.hlsl"
        vertex_def: "TextVertex"
        matrix_slots:
            - MatrixBufferTypeOrthographic
        sampler_slots:
            - UISampler
        needs_shadow: false
        name: "ShaderTextUI"
        dependencies:
          - ShaderAsset

      ShaderTextSDF:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TextSDF.hlsl"
        vertex_def: "TextVertex"
        matrix_slots:
            - MatrixBufferTypeOrthographic
        sampler_slots:
            - UISampler
        needs_shadow: false
        name: "ShaderTextSDF"
        dependencies:
          - ShaderAsset

      DefaultShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\BaseShader.hlsl"
        vertex_def: "SimpleVertex"
        matrix_slots:
            - MatrixBufferType
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "DefaultShader"
        dependencies:
          - ShaderAsset

      TextureBasicShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TextureBasicShader.hlsl"
        vertex_def: "TextureBasicVertex"
        matrix_slots:
            - MatrixBufferType
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "TextureBasicShader"
        dependencies:
          - ShaderAsset

      TextureMapShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TextureMapShader.hlsl"
        vertex_def: "TextureMapVertex"
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "TextureMapShader"
        dependencies:
          - ShaderAsset

      PBRShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\PBRShader.hlsl"
        vertex_def: "TextureMapVertex"
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "PBRShader"
        dependencies:
          - ShaderAsset

      PBRShadowShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\PBRShadowShader.hlsl"
        vertex_def: "TextureMapVertex"
        needs_shadow: true
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
            - LightSpaceMatrices
        sampler_slots:
            - baseSampler
            - ShadowMapSampler
        name: "PBRShadowShader"
        dependencies:
          - ShaderAsset

      ShadowMapShader:
        # Shader para la generaci�n de mapas de sombras. No se usa directamente en la escena,  
        # sino que se utiliza para generar mapas de sombras que luego son usados por otros shaders.
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\ShadowMapShader.hlsl"
        vertex_def: "SimpleVertex"
        matrix_slots:
            - ShadowMapMatrices
        sampler_slots:
            - None
        name: "ShadowMapShader"
        needs_shadow: false
        dependencies:
          - ShaderAsset

      SkyboxShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\SkyboxShader.hlsl"
        vertex_def: "SkyboxVertex"
        matrix_slots:
            - MatrixBufferType
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "SkyboxShader"
        dependencies:
          - ShaderAsset

      ProceduralSkyboxShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\MyProceduralSkyboxShader.hlsl"
        vertex_def: "SimpleVertex"
        # vertex_def: "SkyboxVertex"
        matrix_slots:
            - MatrixBufferType
            - ProceduralSkyboxMatrix
            # - MatrixBufferTypeProceduralSkyBox
            # - ProceduralSkyboxMatrix
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "ProceduralSkyboxShader"
        dependencies:
          - ShaderAsset

      TerrainShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TerrainShader.hlsl"
        vertex_def: "TextureMapVertex"
        needs_shadow: true
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
            - LightSpaceMatrices
            - TerrainBlendBuffer
        sampler_slots:
            - baseSampler
            - ShadowMapSampler
        name: "TerrainShader"
        dependencies:
          - ShaderAsset

      Terrain2Shader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\Terrain2Shader.hlsl"
        vertex_def: "TextureMapVertex"
        needs_shadow: true
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
            - LightSpaceMatrices
            - Terrain2BlendBuffer
            # - FogBuffer
        sampler_slots:
            - baseSampler
            - ShadowMapSampler
        name: "Terrain2Shader"
        dependencies:
          - ShaderAsset

      TerrainTessellation:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\TerrainTessellation.hlsl"
        vertex_def: "SimpleVertex"
        matrix_slots:
            - MatrixBufferType
            - CameraData
        sampler_slots:
            - baseSampler
        needs_shadow: false
        name: "TerrainTessellation"
        dependencies:
          - ShaderAsset

      # Nuevo: Shader del agua (reflejos, refracci�n)
      OceanShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\OceanShader.hlsl"
        vertex_def: "SimpleVertex"
        needs_shadow: false
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData            
            - WaterData
            - TimeData
            - WaterInstance
        sampler_slots:
            - baseSampler
            # - ShadowMapSampler
            # - WaterSampler # Nuevo sampler para reflejo/refracci�n
        name: "OceanShader"
        dependencies:
            - ShaderAsset

      # Nuevo: Shader para el pase de reflejos
      WaterReflectionShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\WaterReflectionShader.hlsl"
        vertex_def: "TextureMapVertex"
        needs_shadow: true
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
            - LightSpaceMatrices
            - TerrainBlendBuffer
        sampler_slots:
            - baseSampler
            - ShadowMapSampler
        name: "WaterReflectionShader"
        dependencies:
          - ShaderAsset

      # Nuevo: Shader para el pase de refracci�n
      WaterRefractionShader:
        type: "ShaderAsset"
        shader_path: "C:\\Users\\joaqu\\source\\repos\\DirectX-Voxelado\\Assets\\Shader\\WaterRefractionShader.hlsl"
        vertex_def: "TextureMapVertex"
        needs_shadow: true
        matrix_slots:
            - MatrixBufferType
            - DirectionalLight
            - CameraData
            - MaterialData
            - TextureTransformations
            - LightSpaceMatrices
            - TerrainBlendBuffer
        sampler_slots:
            - baseSampler
            - ShadowMapSampler
        name: "WaterRefractionShader"
        dependencies:
          - ShaderAsset
Definition:
  Default:
    language: 1 # C++
    type: "Class"
    needs_register: true
    file_level: 3
    register_include: "REGISTER_CONFIG_TYPE"
    register_macro: "REGISTER_CONFIG_MACRO"
    interface_name: "IAssetShaderConfig"
    class_suffix: "Config"
    class_prefix: ""
    inherits_properties:
        - type
        - shader_path
        - vertex_def
        - matrix_slots
        - sampler_slots
        - needs_shadow
        - name
        - dependencies
    # output_path: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\TestConfig\Assets\'
    output_path: 'c:\Users\joaqu\source\repos\DirectX-Voxelado\src\Engine\Core\Config\Assets\' 
