Config:
  UI:
    Items:
      ItemConfig:
        init:
         - Typograph
         - Line
         - Rectangle
         - Panel
      Typgraph:
          font: "Arial"
          initil_size: 12
          letter_spacing: 1.0
          initial_color: "#FFFFFF"
Definition:
  Default:
    language: 1 # C++
    type: "Class"
    needs_register: true
    file_level: 4
    register_include: "REGISTER_CONFIG_TYPE"
    register_macro: "REGISTER_CONFIG_MACRO"
    h_methods_template: ""
    interface_name: "ConfigService"
    class_suffix: "Config"
    class_prefix: ""
    inherits_properties:
      - type
      - enabled
      - texture
      - shader
      - text
      - dependencies
    #output_path: 'C:\Users\joaqu\source\repos\DirectX-Voxelado\TestConfig\Services\'
    output_path: 'c:\Users\joaqu\source\repos\DirectX-Voxelado\src\Engine\Core\Config\Services\'
        